version: '2'
networks: 
  dev: 
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.110.0/24
services: 
  handle:
    image: u03013112/handle:v1
    container_name: 'handle'
    tty: true
    volumes:
        - ../:/src:cached
    working_dir: /src/
    networks:
      - dev
    ports:
      - 0.0.0.0:4444:4444
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
